# Generated by Django 2.1.2 on 2018-11-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='raffle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reputations', to='rifa.Raffle'),
            preserve_default=False,
        ),
    ]
