# Generated by Django 2.1.2 on 2018-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
