# Generated by Django 2.1.2 on 2018-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0004_auto_20181106_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='limit_date',
            field=models.DateTimeField(verbose_name='Data do sorteio'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='qtd_num',
            field=models.IntegerField(verbose_name='Números'),
        ),
    ]
